/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#757c7f",
        "secondary-container": "#dee0ff",
        "on-background": "#2d3337",
        "on-surface": "#2d3337",
        "on-secondary-fixed-variant": "#2d49dc",
        "outline-variant": "#acb3b7",
        "surface-tint": "#006b62",
        "on-tertiary-fixed-variant": "#006a34",
        "tertiary": "#006e36",
        "error": "#ac3434",
        "surface-container-high": "#e3e9ec",
        "on-error-container": "#65000b",
        "background": "#f7f9fb",
        "on-tertiary": "#e8ffe8",
        "on-secondary-container": "#1e3ed2",
        "surface-bright": "#f7f9fb",
        "inverse-primary": "#91feef",
        "secondary-fixed": "#dee0ff",
        "on-error": "#fff7f6",
        "on-primary-fixed": "#00443e",
        "error-container": "#f56965",
        "primary-container": "#83efe1",
        "surface-dim": "#d3dbdf",
        "on-primary-container": "#005951",
        "tertiary-fixed-dim": "#5def8f",
        "primary": "#006b62",
        "on-tertiary-fixed": "#004a22",
        "on-tertiary-container": "#005f2e",
        "on-surface-variant": "#596063",
        "secondary-dim": "#203fd4",
        "secondary": "#314ee0",
        "secondary-fixed-dim": "#ccd2ff",
        "on-secondary-fixed": "#0029b8",
        "primary-fixed": "#83efe1",
        "surface-container-highest": "#dde3e7",
        "on-secondary": "#faf8ff",
        "tertiary-fixed": "#6dfe9c",
        "on-primary-fixed-variant": "#00635b",
        "error-dim": "#70030f",
        "inverse-on-surface": "#9a9d9f",
        "tertiary-dim": "#00602f",
        "on-primary": "#e2fff9",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#74e1d3",
        "tertiary-container": "#6dfe9c",
        "surface-container": "#eaeef1",
        "surface-container-low": "#f1f4f6",
        "surface-variant": "#dde3e7",
        "inverse-surface": "#0b0f10",
        "surface": "#f7f9fb",
        "primary-dim": "#005e56"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
